mysql:
  dsn: "root:root@tcp(localhost:13316)/notification?charset=utf8mb4&collation=utf8mb4_general_ci&parseTime=True&loc=Local&timeout=1s&readTimeout=3s&writeTimeout=3s&multiStatements=true&interpolateParams=true"

redis:
  addr: "127.0.0.1:6379"

etcd:
  addrs:
    - "127.0.0.1:2379"
gprc:
  server:
    port: 8080
    etcdAddrs:
      - "127.0.0.1:2379"

provider:
  key: "test_key"
cache:
  defaultExpiration: 60000000000
  cleanupInterval: 60000000000

pool:
  initGo: 1000
  coreGo: 1500
  maxGo: 2000
  maxIdleTime: 5000000000
  queueSize: 1000
  queueBacklogRate: 0.8

trace:
  zipkin:
    endpoint: "http://localhost:9411/api/v2/spans"
    serviceName: "notification-platform"

jwt:
  key: "test_key"

cron:
  quotaMonthlyReset:
    spec: "0 0 1 1 *"
  loadBusinessLocalCache:
    # 调小的问题是：会不会对数据库造成压力?
    # 你产生的读 QPS  = N(节点数量) * 频率（比如说 1秒钟一次）
    spec: "* * * * *" # 每分钟执行一次，你可以调小，甚至于到 1 秒钟一次

sharding_scheduler:
  maxLockedTablesKey: "maxLockedTablesKey"
  maxLockedTables: 10
  minLoopDuration: 1000000000
  batchSize: 100
  batchSizeAdjuster:
    initBatchSize: 100
    minBatchSize: 50
    maxBatchSize: 200
    adjustStep: 5
    cooldownPeriod: 5000000000
    bufferSize: 128
  errorEvents:
    bitRingSize: 128
    rateThreshold: 0.8
    consecutiveCount: 3
