// Code generated by MockGen. DO NOT EDIT.
// Source: ./notification.go
//
// Generated by this command:
//
//	mockgen -source=./notification.go -destination=./mocks/notification.mock.go -package=notificationmocks -typed Service
//

// Package notificationmocks is a generated GoMock package.
package notificationmocks

import (
	context "context"
	domain "go-notification/internal/domain"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockService is a mock of Service interface.
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
	isgomock struct{}
}

// MockServiceMockRecorder is the mock recorder for MockService.
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance.
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// FindReadyNotifications mocks base method.
func (m *MockService) FindReadyNotifications(ctx context.Context, offiset, limit int) ([]domain.Notification, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindReadyNotifications", ctx, offiset, limit)
	ret0, _ := ret[0].([]domain.Notification)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindReadyNotifications indicates an expected call of FindReadyNotifications.
func (mr *MockServiceMockRecorder) FindReadyNotifications(ctx, offiset, limit any) *MockServiceFindReadyNotificationsCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindReadyNotifications", reflect.TypeOf((*MockService)(nil).FindReadyNotifications), ctx, offiset, limit)
	return &MockServiceFindReadyNotificationsCall{Call: call}
}

// MockServiceFindReadyNotificationsCall wrap *gomock.Call
type MockServiceFindReadyNotificationsCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockServiceFindReadyNotificationsCall) Return(arg0 []domain.Notification, arg1 error) *MockServiceFindReadyNotificationsCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockServiceFindReadyNotificationsCall) Do(f func(context.Context, int, int) ([]domain.Notification, error)) *MockServiceFindReadyNotificationsCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockServiceFindReadyNotificationsCall) DoAndReturn(f func(context.Context, int, int) ([]domain.Notification, error)) *MockServiceFindReadyNotificationsCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetByKeys mocks base method.
func (m *MockService) GetByKeys(ctx context.Context, bizID int64, keys ...string) ([]domain.Notification, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, bizID}
	for _, a := range keys {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetByKeys", varargs...)
	ret0, _ := ret[0].([]domain.Notification)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByKeys indicates an expected call of GetByKeys.
func (mr *MockServiceMockRecorder) GetByKeys(ctx, bizID any, keys ...any) *MockServiceGetByKeysCall {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, bizID}, keys...)
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByKeys", reflect.TypeOf((*MockService)(nil).GetByKeys), varargs...)
	return &MockServiceGetByKeysCall{Call: call}
}

// MockServiceGetByKeysCall wrap *gomock.Call
type MockServiceGetByKeysCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockServiceGetByKeysCall) Return(arg0 []domain.Notification, arg1 error) *MockServiceGetByKeysCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockServiceGetByKeysCall) Do(f func(context.Context, int64, ...string) ([]domain.Notification, error)) *MockServiceGetByKeysCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockServiceGetByKeysCall) DoAndReturn(f func(context.Context, int64, ...string) ([]domain.Notification, error)) *MockServiceGetByKeysCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
